import { NewsItem, OfferItem } from "@/lib/api";

export const mockNews: NewsItem[] = [
  {
    id: "fallback-news-1",
    title: "Rain advisory: stagger sowing to manage uneven pre-monsoon showers",
    summary: "Field officers recommend phased sowing and moisture checks before second irrigation.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Monsoon_rain_in_Kerala.jpg",
    url: "https://mausam.imd.gov.in/",
    source: "Fallback Feed",
    category: "weather",
    region: "India",
    published_at: "2026-04-10T08:00:00Z",
  },
  {
    id: "fallback-news-2",
    title: "State mandi board expands weekend procurement windows",
    summary: "Additional weekend procurement slots announced for select districts.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Wheat_market.jpg",
    url: "https://agmarknet.gov.in/",
    source: "Fallback Feed",
    category: "market",
    region: "India",
    published_at: "2026-04-09T11:30:00Z",
  },
  {
    id: "fallback-news-3",
    title: "Soil testing vans available at block level this month",
    summary: "Mobile labs to publish nutrient cards within 72 hours of sample collection.",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Soil_profile.jpg",
    url: "https://soilhealth.dac.gov.in/",
    source: "Fallback Feed",
    category: "soil",
    region: "India",
    published_at: "2026-04-08T15:20:00Z",
  },
];

export const mockOffers: OfferItem[] = [
  {
    id: "offer-pmkisan",
    title: "PM-KISAN annual income support",
    description: "Eligible farmer families receive INR 6,000 per year in three instalments under the PM-KISAN scheme.",
    provider: "Government of India",
    url: "https://pmkisan.gov.in/",
    discount_percent: 0,
    crop: "All",
    region: "India",
    valid_until: "2026-12-31T23:59:59Z",
    published_at: "2026-04-15T09:00:00Z",
  },
  {
    id: "offer-pmksy",
    title: "Micro-irrigation subsidy under PMKSY",
    description: "Subsidy support is available for drip and sprinkler irrigation to improve water efficiency.",
    provider: "Ministry of Agriculture",
    url: "https://pmksy.gov.in/",
    discount_percent: 0,
    crop: "All",
    region: "India",
    valid_until: "2026-12-31T23:59:59Z",
    published_at: "2026-04-15T09:10:00Z",
  },
  {
    id: "offer-soil-health",
    title: "Free soil health card and sample testing",
    description: "Farmers can get soil sample testing and nutrient recommendations through the Soil Health Card program.",
    provider: "Department of Agriculture",
    url: "https://soilhealth.dac.gov.in/",
    discount_percent: 0,
    crop: "All",
    region: "India",
    valid_until: "2026-12-31T23:59:59Z",
    published_at: "2026-04-15T09:20:00Z",
  },
  {
    id: "offer-enam",
    title: "Digital mandi access with eNAM",
    description: "Access real-time prices and trade opportunities by registering on the National Agriculture Market.",
    provider: "eNAM",
    url: "https://www.enam.gov.in/",
    discount_percent: 0,
    crop: "All",
    region: "India",
    valid_until: "2026-12-31T23:59:59Z",
    published_at: "2026-04-15T09:30:00Z",
  },
  {
    id: "offer-kcc",
    title: "Kisan Credit Card farm credit access",
    description: "Low-cost seasonal credit support for crop production, post-harvest expenses, and allied activities.",
    provider: "NABARD / Banks",
    url: "https://www.nabard.org/",
    discount_percent: 0,
    crop: "All",
    region: "India",
    valid_until: "2026-12-31T23:59:59Z",
    published_at: "2026-04-15T09:40:00Z",
  },
  {
    id: "offer-agri-infra",
    title: "Agriculture Infrastructure Fund support",
    description: "Concessional credit support for post-harvest infrastructure and community assets.",
    provider: "Agriculture Infrastructure Fund",
    url: "https://agriinfra.dac.gov.in/",
    discount_percent: 0,
    crop: "All",
    region: "India",
    valid_until: "2026-12-31T23:59:59Z",
    published_at: "2026-04-15T09:50:00Z",
  },
];
